# Generated by Django 5.2.1 on 2025-08-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rest_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance_evaluation', models.CharField(blank=True, max_length=255, null=True)),
                ('special_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_entitlements', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absence', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalties', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_deduction_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_deduction_days', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_receipts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_salaries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
