# Generated by Django 5.2.1 on 2025-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('APPROVE', 'قبول مبدئي'), ('REJECT', 'رفض مبدئي')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='advanceperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('advance_type',), name='unique_active_period_per_type'),
        ),
    ]
