# Generated by Django 5.2.1 on 2025-08-27 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0002_advancerequest_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'فترة السلفة', 'verbose_name_plural': 'فترات السلف'},
        ),
        migrations.AlterModelOptions(
            name='advancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب سلفة', 'verbose_name_plural': 'طلبات السلف'},
        ),
        migrations.RemoveConstraint(
            model_name='advanceperiod',
            name='unique_active_period_per_type',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='admin_decision',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='decided_at',
        ),
        migrations.RemoveField(
            model_name='advancerequest',
            name='frozen',
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='user_locked',
            field=models.BooleanField(default=False, help_text='قفل تعديل الموظف بعد قبول/رفض مبدئي.'),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='advance_type',
            field=models.CharField(choices=[('FIRST', 'السلفة الأولى'), ('SECOND', 'السلفة الثانية')], help_text='نوع السلفة المرتبطة بهذه الفترة (الأولى/الثانية).', max_length=10),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='end_date',
            field=models.DateField(help_text='تاريخ نهاية نافذة التقديم.'),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='لو مفعّلة، تُعد النافذة الحالية المعتمدة لهذا النوع.'),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='start_date',
            field=models.DateField(help_text='تاريخ بداية نافذة التقديم.'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='advance_type',
            field=models.CharField(choices=[('FIRST', 'السلفة الأولى'), ('SECOND', 'السلفة الثانية')], help_text='نوع السلفة المطلوبة (الأولى/الثانية).', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='قيمة السلفة المطلوبة.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ إنشاء الطلب.'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='locked',
            field=models.BooleanField(default=False, help_text='قفل نهائي يمنع التعديل بعد التأكيد.'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات إضافية للطلب (اختياري).'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='period',
            field=models.ForeignKey(help_text='الفترة التي قُدم ضمنها هذا الطلب.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='advances.advanceperiod'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'تحت المراجعة'), ('APPROVED', 'تم القبول'), ('REJECTED', 'تم الرفض')], default='UNDER_REVIEW', help_text='حالة الطلب الحالية.', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ آخر تعديل.'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='user',
            field=models.ForeignKey(help_text='الموظف صاحب الطلب.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
