# Generated by Django 5.2.1 on 2025-08-28 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0003_alter_advanceperiod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceperiod',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='advancerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('UNDER_REVIEW', 'تحت المراجعة'), ('APPROVED', 'تم القبول'), ('REJECTED', 'تم الرفض')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='advance_type',
            field=models.CharField(choices=[('FIRST', 'السلفة الأولى'), ('SECOND', 'السلفة الثانية')], max_length=10),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advanceperiod',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='advance_type',
            field=models.CharField(choices=[('FIRST', 'السلفة الأولى'), ('SECOND', 'السلفة الثانية')], max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='advances.advanceperiod'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'تحت المراجعة'), ('APPROVED', 'تم القبول'), ('REJECTED', 'تم الرفض')], default='UNDER_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='user_locked',
            field=models.BooleanField(default=False),
        ),
    ]
