# Generated by Django 5.2.1 on 2025-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
