# Generated by Django 5.2.1 on 2025-09-08 14:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقمًا.', regex='^\\d{14}$')])),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقمًا.', regex='^\\d{11}$')])),
                ('address', models.CharField(blank=True, max_length=250)),
                ('borrower_type', models.CharField(choices=[('employee', 'ضمن الموظفين'), ('external', 'خارج الموظفين')], default='employee', max_length=10)),
                ('loans_count', models.PositiveIntegerField(default=0)),
                ('loans_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loans_total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loans_total_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'مستمر'), ('closed', 'مكتمل'), ('bad_debt', 'ديون معدومة')], default='active', max_length=10)),
                ('repayment_type', models.CharField(choices=[('monthly', 'أقساط شهرية'), ('oneoff', 'دفعة واحدة')], max_length=10)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_collection_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='loans.loan')),
            ],
        ),
    ]
